### ISSUE TITLE
ActiveRecord association trouble

### ISSUE THREAD

**Issue by MeredithS** [MeredithS/WikiNutrition#1]
Hi Anna,
I think I am having trouble understanding the relationship between the following tables.  I know we talked about it in our 5 min one on one but I think I am getting confused with the bigger picture now.

So I have these three tables:

articles                article_edit_times         edit_times          users
id                          articles_id                       id                       id
                            edit_times_id
                             users_id

My classes look something like this:

class Article <ActiveRecord::Base
    has_many :users, through: :article_edit_times
end

class EditTime <ActiveRecord::Base
    has_many :articles, through: :article_edit_times
end

class User <ActiveRecord::Base
    has_many :edit_times, through: :article_edit_times
end

class ArticleEditTime <ActiveRecord::Base
    belongs_to :article
    belongs_to :edit_time
    belongs_to :user
end

I think I set it up how we discussed today. Am I supposed to be able to call edit_times on an article to see all the times the article was edited? like this:

a1=Article.find(1)
a1.edit_times
or 
user=User.find(1)
user.edit_times
or
edit=EditTime.find(1) 
edit.articles to see what articles where edited at a specific time?

when I try to do this I am getting undefined method.  I have tried changing the associations and calling .edit_times differently but nothing seems to work.

Please let me know if I need to provide further information.

Thank you

**Comment by annarankin** [comment]
Hey Meredith! I'll take a look at this either later tonight or tomorrow
morning and let you know what I see. Keep me in the loop!

**Comment by MeredithS** [comment]
@annarankin Thanks for the fast response!  I FINALLY figured it out!  I'm finally on my way again!  Thanks so much!

**Comment by annarankin** [comment]
Sweet!!
