### ISSUE TITLE
.edit_times is not working for only one of the three associations

### ISSUE THREAD

**Issue by MeredithS** [MeredithS/WikiNutrition#2]
Hi Anna,

I have a table that "joins" three id's together:

``` ruby
Article_edit_times:
article_id
user_id
edit_time_id
```

I have the associations set up between the 4 classes like this:

``` ruby
class Article <ActiveRecord::Base
    has_many :article_edit_times 
    has_many :edit_times, through: :article_edit_times
end

class EditTime <ActiveRecord::Base
    has_many :article_edit_times
    has_many :articles, through: :article_edit_times
    has_many :users, through: :article_edit_times
end

class User <ActiveRecord::Base
    has_many :article_edit_times
    has_many :edit_times, through: :article_edit_times
end

class ArticleEditTime <ActiveRecord::Base
    belongs_to :article
    belongs_to :edit_time
    belongs_to :user
end
```

After I edit an article and I go into pry this is what I get:

``` ruby
a1=Article.find(1)
=> #<Article:0x007fed748632b0
 id: 1,
 title: "Veggies",
 date_published: 2015-12-01 08:37:00 UTC,
 content: "Veggies, *soo* Yummy",
 img_url: "http://www.valeotraining.com/wp-content/uploads/2013/04/veggies-1.jpg",
 user_id: 1>

EditTime.all
EditTime:0x007fed7576af88 id: 1, time: 2015-12-04 19:21:35 UTC
 EditTime:0x007fed7576ae48 id: 2, time: 2015-12-04 19:21:50 UTC

u1=User.find(1)
=> #<User:0x007fed751c3fa8
 id: 1,
 user_name: "MerBear",
 password_digest: "$2a$10$jtYFigUO5Q3FqZsTvlf/tuJU6VshmaollHL25pbpH8joAH0DF6D7y",
 f_name: "Meredith",
 l_name: "Salguero",
 e_mail: "MSalguero@gmail.com">

u1.edit_times
EditTime:0x007fed748f24d8 id: 1, time: 2015-12-04 19:21:35 UTC
EditTime:0x007fed748f2398 id: 2, time: 2015-12-04 19:21:50 UTC
------Here we are getting all the edit times that user one has done-----

e1=EditTime.find(1)
=> #<EditTime:0x007fed74385bf8 id: 1, time: 2015-12-04 19:21:35 UTC>

e1.articles
=> [#<Article:0x007fed74919420
  id: 1,
  title: "Veggies",
  date_published: 2015-12-01 08:37:00 UTC,
  content: "Veggies, *soo* Yummy",
  img_url: "http://www.valeotraining.com/wp-content/uploads/2013/04/veggies-1.jpg",
  user_id: 1>]
----Here I am getting all the articles edited at edit_time 1
```

BUT IF I TRY

``` ruby

a1.edit_times
=> []
```

-----I get an empty array!!!!

Yet when I do this:

``` ruby
ArticleEditTime.all
=> [#<ArticleEditTime:0x007fed75730db0 article_id: "1", edit_time_id: 1, user_id: 1>,
 #<ArticleEditTime:0x007fed75730c70 article_id: "1", edit_time_id: 2, user_id: 1>]
---It clearly shows that I have multiple edit times for Article1 and my association works one way but not the other!  e1.articles works but a1.edit_times does not!

```

All of this was working last night when I pushed so I can't think of anything that I did that would break the code and my associations have not changed!

PLEASE HELP!!!!

**Comment by MeredithS** [comment]
@annarankin I just realized my cut and paste of EditTimes.all didn't come out!

this is it:

EditTime.all
EditTime:0x007fed7576af88 id: 1, time: 2015-12-04 19:21:35 UTC
 EditTime:0x007fed7576ae48 id: 2, time: 2015-12-04 19:21:50 UTC

u1.edit_times
EditTime:0x007fed748f24d8 id: 1, time: 2015-12-04 19:21:35 UTC,
 EditTime:0x007fed748f2398 id: 2, time: 2015-12-04 19:21:50 UTC

**Comment by MeredithS** [comment]
hhhmm @annarankin not sure why it isn't cutting and pasting properly.  Maybe this time it will work

EditTime.all
#<EditTime:0x007fed7576af88 id: 1, time: 2015-12-04 19:21:35 UTC>,
 #<EditTime:0x007fed7576ae48 id: 2, time: 2015-12-04 19:21:50 UTC>

**Comment by annarankin** [comment]
Hey Meredith, looking at this now! Can you push up the most recent version of your code?

**Comment by MeredithS** [comment]
@annarankin lol! I pushed up and then saw your message!  perfect timing!

**Comment by annarankin** [comment]
Hey Meredith, I re-ran your schema and uncommented the commented-out lines in your seeds file, and I'm getting article edit times now.

**Comment by MeredithS** [comment]
@annarankin I figured it out!  When the Article_edit_times was being created in the server the user_id was being passed as a string since it was a session[:user_id].  So when I tried to find it using an integer it wouldn't work!
